---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

spec/spec_helper.rb:
  mock_with: ':rspec'

.travis.yml:
  branches:
    - develop
  includes:
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec
